# Generated by Django 3.1.2 on 2020-12-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201201_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupgame',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
