# Generated by Django 3.1.2 on 2020-12-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pickupgame_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgame',
            name='lat',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='pickupgame',
            name='lng',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='pickupgame',
            name='numPlayers',
            field=models.IntegerField(default=False),
        ),
    ]
