# Generated by Django 3.1.2 on 2020-12-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201201_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgame',
            name='active',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
