# Generated by Django 3.1.2 on 2020-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pickupgame_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupgame',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
